version: '3'
services:
  mymongo:
    image: mongo:latest
    volumes:
      - ./_data:/data/db
    ports:
      - 27017:27017
      - 28017:28017
  myapp:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://mymongo:27017/mydb
      - MONGODB_STATUS_HOST=mymongo
      - MONGODB_STATUS_PORT=28017
    ports:
      - 8080:8080
